### ISSUE TITLE
Error "export 'markerClusterGroup' (imported as 'L') was not found in 'leaflet'" in file leaflet-markercluster.directive.js 

### ISSUE THREAD

**Issue by turbolego** [bluehalo/ngx-leaflet-markercluster#70]
This setup has worked for weeks, and today it suddenly does not work.
Error is coming from `node_modules/@asymmetrik/ngx-leaflet-markercluster/__ivy_ngcc__/dist/leaflet-markercluster/leaflet-markercluster.directive.js `
Tried on two different computers.

I have tried to delete node_modules and package-lock.json and running npm install again.

npm 8.15.0
node v16.17.0

package.json
```
"dependencies": {
    "@asymmetrik/ngx-leaflet": "^8.1.0",
    "@asymmetrik/ngx-leaflet-markercluster": "^5.0.1",
    "@types/leaflet.markercluster": "^1.4.5",
    "leaflet": "^1.7.1",
    "leaflet.markercluster": "^1.5.1",
    "proj4": "^2.7.5",
    "proj4leaflet": "^1.0.2",
},
"devDependencies": {
    "@types/leaflet": "^1.7.5",
    "@types/proj4": "^2.5.2",
    "@types/proj4leaflet": "^1.0.6",
}
```
Error:
```
Error: ./node_modules/@asymmetrik/ngx-leaflet-markercluster/__ivy_ngcc__/dist/leaflet-markercluster/leaflet-markercluster.directive.js 18:34-54
"export 'markerClusterGroup' (imported as 'L') was not found in 'leaflet'
    at HarmonyImportSpecifierDependency._getErrors (/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:1463:22)
    at /frontend/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:1258:10
    at _next0 (eval at create (/frontend/node_modules/@angular-devkit/build-angular/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:1)
    at eval (eval at create (/frontend/node_modules/@angular-devkit/build-angular/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 @ ./node_modules/@asymmetrik/ngx-leaflet-markercluster/__ivy_ngcc__/dist/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

```

**Comment by reblace** [comment]
Usually when this happens its because a new minor or patch version of either Leaflet or the typings came out and aren't really backwards compatible.

I think I saw another thread say that Leaflet pushed a new version (1.9) and it may have cause this issue. You can try pinning to 1.8 and see if it fixes it.

**Comment by turbolego** [comment]
`"leaflet": "1.8.0",` works! Thank you so much! :smile:
