### ISSUE TITLE
TypeError: Z.markerClusterGroup is not a function   

### ISSUE THREAD

**Issue by Stan92** [bluehalo/ngx-leaflet-markercluster#89]
Hi,
I m facing a strange bug.. it perfectly work in dev env but once I build the app I get an error

my packages

```
    "@bluehalo/ngx-leaflet": "^18.0.2",
    "@bluehalo/ngx-leaflet-markercluster": "^18.0.1",
   "leaflet": "^1.9.4",
   "leaflet.markercluster": "^1.5.3",

```
The error

```
chunk-BIIIJQ6J.js:7 ERROR 
TypeError: Z.markerClusterGroup is not a function
    at f.ngOnInit (chunk-XPW44FIX.js:1:34715)
    at Hg (chunk-BIIIJQ6J.js:7:20147)
```
This the part of the code that generates the error
```
        ngOnInit() {
            this.leafletDirective.init();
            let t = this.leafletDirective.getMap();
            **this.markerClusterGroup = Z.markerClusterGroup(this.markerClusterOptions),**
            this.markerClusterGroup.addTo(t),
            this.setData(this.markerData),
            this.markerClusterReady.emit(this.markerClusterGroup)
        }

```

```
  <div class="min-h-80"
       leaflet
       [leafletLayers]="layers"
       [leafletOptions]="options"
       (leafletMapReady)="onMapReady($event)"
       [leafletMarkerCluster]="markerClusterData"
       [leafletMarkerClusterOptions]="markerClusterOptions"
       (leafletMarkerClusterReady)="markerClusterReady($event)"></div>

```

I probably missed something.. but can't figure out.

**Comment by bmulder-innoseis** [comment]
See also #91, I have the same issue on angular 18.

**Comment by reblace** [comment]
This is a known interop issue between Angular's esbuild builder and `leaflet.markercluster`'s UMD bundling — not specific to any one Angular version. The workarounds and root cause analysis are now documented in the [README Troubleshooting section](https://github.com/bluehalo/ngx-leaflet-markercluster#troubleshooting). For ongoing investigation into a proper fix, see #107. Closing this one as a duplicate.
